# Generated by Django 3.0.6 on 2020-05-24 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('refri', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='recipe.Recipe'),
        ),
        migrations.AddField(
            model_name='honor',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Icon'),
        ),
        migrations.AddField(
            model_name='honor',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe'),
        ),
        migrations.AddField(
            model_name='honor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barcode',
            name='basicitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='refri.BasicItem'),
        ),
        migrations.AddField(
            model_name='barcode',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='refri.Item'),
        ),
    ]
