# Generated by Django 3.0.6 on 2020-05-31 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200524_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='image',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='file',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='image',
        ),
    ]
