# Generated by Django 3.0.6 on 2020-05-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200531_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='icon'),
        ),
        migrations.AddField(
            model_name='notice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
