# Generated by Django 3.0.6 on 2020-07-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20200531_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='barcode_num',
            field=models.CharField(default='0000000000000', max_length=13),
        ),
        migrations.AlterField(
            model_name='barcode',
            name='item_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
