# Generated by Django 3.0.6 on 2020-07-22 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20200722_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='icon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Icon'),
            preserve_default=False,
        ),
    ]
