# Generated by Django 3.0.6 on 2020-08-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_userdata_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BAR_CD', models.CharField(default='0000000000000', max_length=50)),
                ('PRDLST_DCNM', models.CharField(default='category', max_length=50)),
                ('PRDLST_NM', models.CharField(default='name', max_length=50)),
                ('BSSH_NM', models.CharField(default='corp', max_length=50)),
                ('PRMS_DT', models.CharField(default='make start date', max_length=50)),
                ('CLSBIZ_DT', models.CharField(default='', max_length=50)),
                ('INDUTY_NM', models.CharField(default='corp category', max_length=50)),
                ('SITE_ADDR', models.CharField(default='address', max_length=50)),
                ('POG_DAYCNT', models.CharField(default='shelf life', max_length=50)),
                ('END_DT', models.CharField(default='make finish date', max_length=50)),
                ('PRDLST_REPORT_NO', models.CharField(default='report number', max_length=50)),
            ],
        ),
    ]
