# Generated by Django 3.0.6 on 2020-08-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='BSSH_NM',
            field=models.CharField(blank=True, default='corp', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='CLSBIZ_DT',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='END_DT',
            field=models.CharField(blank=True, default='make finish date', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='INDUTY_NM',
            field=models.CharField(blank=True, default='corp category', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='POG_DAYCNT',
            field=models.CharField(blank=True, default='shelf life', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='PRDLST_DCNM',
            field=models.CharField(blank=True, default='category', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='PRDLST_NM',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='PRDLST_REPORT_NO',
            field=models.CharField(blank=True, default='report number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='PRMS_DT',
            field=models.CharField(blank=True, default='make start date', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='SITE_ADDR',
            field=models.CharField(blank=True, default='address', max_length=50, null=True),
        ),
    ]
