# Generated by Django 3.0.6 on 2020-05-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrigerator',
            name='memo_num',
            field=models.IntegerField(default=0),
        ),
    ]
