# Generated by Django 3.0.6 on 2020-05-24 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200524_1258'),
        ('refri', '0002_refrigerator_memo_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicitem',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='basicitem',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Icon'),
        ),
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Icon'),
        ),
    ]
