# Generated by Django 3.0.6 on 2020-07-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refri', '0003_auto_20200524_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='create_type',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='memo',
            name='content',
            field=models.TextField(),
        ),
    ]
